# 21 jobs
# wandb:
#   group:  score-parallel

just_score_model: true
save_folder: /n/netscratch/sham_lab/Everyone/dclm/color_filter/scores/dclm-filtered_core-train-tasks_3-to-5/conditional
max_duration: 60000
global_train_batch_size: 256
device_train_microbatch_size: 256 
restore_dataloader: false # restart from step 0
reset_optimizer_state: true
reset_trainer_state: true
seed: 1
sweep:
  - load_path:
      - conditional_all
    load_checkpoint_type: unsharded
    data_start_step: # whole dataset in parallel
      - 0
      - 60000
      - 120000
      - 180000